name: 'Terraform CI/CD'

on:
  workflow_call:
    
#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_USE_OIDC: true
  # Add these for backend authentication
  ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY_TFSTATE }}

jobs:
  # Run Terraform
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.1.7

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform -chdir=infrastructure-azure/ init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform -chdir=infrastructure-azure/ plan -out=tfplan -var-file=prod.tfvars

    - name: Manual Approval
      if: |
        github.event_name == 'push' && 
        github.ref == 'refs/heads/master'
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: cassiano-kretzmann,michaelpoatek
        minimum-approvals: 1
        issue-title: 'Applying Terraform to environment'
        issue-body: "Please verify the 'Terraform Plan' result from the previous step before approving this deployment."

    - name: Terraform Apply
      if: |
        github.event_name == 'push' && 
        github.ref == 'refs/heads/master'
      run: terraform -chdir=infrastructure-azure/ apply -auto-approve tfplan